# Generated by Django on 2026-01-13 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_recurringinvoice'),
        ('business', '0002_client'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('days_before_due', models.IntegerField(default=3)),
                ('send_on_overdue', models.BooleanField(default=True)),
                ('subject_template', models.CharField(blank=True, max_length=255, null=True)),
                ('text_template', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_rules', to='business.business')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_rules', to='accounts.user')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_rules', to='invoices.invoice')),
            ],
        ),
    ]
