# Generated by Django 5.2.9 on 2026-07-10 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='logo',
        ),
    ]
